application: x486321
version: 1
runtime: go
api_version: go1

handlers:
- url: /robots\.txt
  static_files: static/robots.txt
  upload: static/robots.txt

- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /-/static
  static_dir: static
  expiration: 30d

- url: /.*
  script: _go_app

skip_files: |
 ^(.*/)?(
 (app\.yaml)|
 (app\.yml)|
 (index\.yaml)|
 (index\.yml)|
 (#.*#)|
 (.*~)|
 (.*\.py[co])|
 (.*/RCS/.*)|
 (\..*)|
 (tools/.*)|
 )$